#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

info "Checking dependencies..."
command -v docker >/dev/null 2>&1 || error "Docker is not installed."
command -v openssl >/dev/null 2>&1 || error "openssl is not installed."
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 is not available."

DOCKER_VER=$(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
info "Docker ${DOCKER_VER}"
info "Compose $(docker compose version --short)"

if ! command -v nvidia-smi >/dev/null 2>&1; then
    warn "No NVIDIA GPU detected. EcoDB requires CUDA for embeddings."
    read -p "Continue anyway? [y/N] " -n 1 -r; echo
    [[ $REPLY =~ ^[Yy]$ ]] || exit 1
fi

info "Checking disk space..."
if [[ "$(uname)" == "Darwin" ]]; then
    AVAILABLE_GB=$(df -g . | tail -1 | awk '{print $4}')
else
    AVAILABLE_GB=$(df -BG . | tail -1 | awk '{print $4}' | tr -d 'G')
fi
if [ "${AVAILABLE_GB:-0}" -lt 40 ]; then
    warn "Less than 40 GB free (${AVAILABLE_GB}G). First boot needs ~35 GB."
    read -p "Continue anyway? [y/N] " -n 1 -r; echo
    [[ $REPLY =~ ^[Yy]$ ]] || exit 1
fi

if [ -f .env ]; then
    warn ".env already exists. Overwrite?"
    read -p "This will reset all secrets. Continue? [y/N] " -n 1 -r; echo
    [[ $REPLY =~ ^[Yy]$ ]] || { info "Keeping existing .env."; exit 0; }
fi

info "Generating secrets..."
DB_PASS=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
API_PEPPER=$(openssl rand -hex 32)

USE_SEED=false
echo ""
info "EcoDB can install a demo dataset on first boot."
info "The demo includes example memories that teach you how the system works."
echo ""
read -p "Install demo dataset? [Y/n] " -n 1 -r; echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    USE_SEED=true
    info "Demo dataset will be loaded on first boot."
else
    info "Starting with empty database."
fi

cat > .env << EOF
# Generated by setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
ECODB_DB_PASSWORD=${DB_PASS}
ECODB_ENV=development
ECODB_JWT_SECRET=${JWT_SECRET}
ECODB_API_KEY_PEPPER=${API_PEPPER}
ECODB_CORS_ORIGINS=http://localhost:8080,http://localhost:8091
ECODB_API_KEY=
EOF

chmod 600 .env
info ".env generated with random secrets."

if ! grep -q "INTERNAL_BROADCAST_SECRET" .env 2>/dev/null; then
    BROADCAST_SECRET=$(openssl rand -hex 32)
    echo "INTERNAL_BROADCAST_SECRET=$BROADCAST_SECRET" >> .env
fi

# ENCRYPTION_KEY for LLM provider key encryption (Fernet — 32-byte url-safe base64).
# Required by the providers API and the cell worker. Without it, POST /providers 500s.
if ! grep -q "ENCRYPTION_KEY" .env 2>/dev/null; then
    if command -v python3 >/dev/null 2>&1; then
        ENC_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null)
    fi
    if [ -z "$ENC_KEY" ]; then
        # Fallback: Fernet keys are urlsafe-base64 of 32 random bytes.
        ENC_KEY=$(openssl rand -base64 32 | tr '+/' '-_')
    fi
    echo "ENCRYPTION_KEY=$ENC_KEY" >> .env
fi

mkdir -p media
info "Created media/ directory for image storage."

echo ""
info "Setup complete. Next steps:"
echo ""
if [ "$USE_SEED" = "true" ]; then
    echo "  1. Start: docker compose -f docker-compose.yml -f docker-compose.seed.yml up --build -d"
else
    echo "  1. Start: docker compose up --build -d"
fi
echo "  2. Wait for first boot (models download ~35 GB)"
echo "  3. Generate API key: docker exec ecodb-api python bootstrap_first_apikey.py"
echo "  4. Add key to .env: ECODB_API_KEY=ecodb_..."
echo "  5. Restart MCP: docker compose restart mcp"
