<#
EcoDB setup for Windows (PowerShell). Equivalent of scripts/setup.sh.
Generates .env with random secrets and prepares the first boot.

Run from the repo root:
    powershell -ExecutionPolicy Bypass -File scripts\setup.ps1
#>

$ErrorActionPreference = 'Stop'

function Info($m) { Write-Host "[INFO] $m"  -ForegroundColor Green }
function Warn($m) { Write-Host "[WARN] $m"  -ForegroundColor Yellow }
function Fail($m) { Write-Host "[ERROR] $m" -ForegroundColor Red; exit 1 }

function New-HexSecret([int]$bytes) {
    $buf = New-Object 'System.Byte[]' $bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($buf)
    -join ($buf | ForEach-Object { '{0:x2}' -f $_ })
}

Info "Checking dependencies..."
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { Fail "Docker is not installed." }
docker compose version | Out-Null
if ($LASTEXITCODE -ne 0) { Fail "Docker Compose v2 is not available." }
Info "Docker $((docker --version))"

if (-not (Get-Command nvidia-smi -ErrorAction SilentlyContinue)) {
    Warn "No NVIDIA GPU detected. EcoDB requires CUDA for embeddings."
    $r = Read-Host "Continue anyway? [y/N]"
    if ($r -notmatch '^[Yy]') { exit 1 }
}

if (Test-Path .env) {
    Warn ".env already exists. Overwriting resets all secrets."
    $r = Read-Host "Continue? [y/N]"
    if ($r -notmatch '^[Yy]') { Info "Keeping existing .env."; exit 0 }
}

Info "Generating secrets..."
$DbPass    = New-HexSecret 16
$JwtSecret = New-HexSecret 32
$ApiPepper = New-HexSecret 32

$UseSeed = $false
Write-Host ""
Info "EcoDB can install a demo dataset on first boot (example memories)."
$r = Read-Host "Install demo dataset? [Y/n]"
if ($r -notmatch '^[Nn]') { $UseSeed = $true; Info "Demo dataset will be loaded on first boot." }
else { Info "Starting with empty database." }

$stamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$lines = @(
    "# Generated by setup.ps1 - $stamp"
    "ECODB_DB_PASSWORD=$DbPass"
    "ECODB_ENV=development"
    "ECODB_JWT_SECRET=$JwtSecret"
    "ECODB_API_KEY_PEPPER=$ApiPepper"
    "ECODB_CORS_ORIGINS=http://localhost:8080,http://localhost:8091"
    "ECODB_API_KEY="
)
# UTF-8 WITHOUT BOM — docker compose misparses a .env that starts with a BOM.
$content = ($lines -join "`n") + "`n"
$envPath = Join-Path (Get-Location) ".env"
[System.IO.File]::WriteAllText($envPath, $content, (New-Object System.Text.UTF8Encoding $false))
Info ".env generated with random secrets."

if (-not (Select-String -Path .env -Pattern "INTERNAL_BROADCAST_SECRET" -Quiet -ErrorAction SilentlyContinue)) {
    $broadcastSecret = New-HexSecret 32
    Add-Content -Path .env -Value "INTERNAL_BROADCAST_SECRET=$broadcastSecret" -Encoding utf8
}

# ENCRYPTION_KEY for LLM provider key encryption (Fernet = urlsafe base64 of 32 random bytes).
# Required by providers API + cell worker. Without it, POST /providers 500s.
if (-not (Select-String -Path .env -Pattern "ENCRYPTION_KEY" -Quiet -ErrorAction SilentlyContinue)) {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $encKey = [Convert]::ToBase64String($bytes).Replace('+','-').Replace('/','_')
    Add-Content -Path .env -Value "ENCRYPTION_KEY=$encKey" -Encoding utf8
}

if (-not (Test-Path media)) { New-Item -ItemType Directory -Path media | Out-Null }
Info "Created media/ directory for image storage."

Write-Host ""
Info "Setup complete. Next steps:"
Write-Host ""
if ($UseSeed) {
    Write-Host "  1. Start: docker compose -f docker-compose.yml -f docker-compose.seed.yml up --build -d"
} else {
    Write-Host "  1. Start: docker compose up --build -d"
}
Write-Host "  2. Wait for first boot (models download ~35 GB)"
Write-Host "  3. Generate API key: docker exec ecodb-api python bootstrap_first_apikey.py"
Write-Host "  4. Add the printed key to .env: ECODB_API_KEY=ecodb_..."
Write-Host "  5. Restart MCP: docker compose restart mcp"
