<#
KnowTwin setup for Windows (PowerShell). Equivalent of scripts/setup.sh.
Generates .env with random secrets that feed docker-compose.

Run from the repo root:
    powershell -ExecutionPolicy Bypass -File scripts\setup.ps1
#>

$ErrorActionPreference = 'Stop'

function Info($m) { Write-Host "[INFO] $m"  -ForegroundColor Green }
function Warn($m) { Write-Host "[WARN] $m"  -ForegroundColor Yellow }
function Fail($m) { Write-Host "[ERROR] $m" -ForegroundColor Red; exit 1 }

function New-HexSecret([int]$bytes) {
    $buf = New-Object 'System.Byte[]' $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    -join ($buf | ForEach-Object { '{0:x2}' -f $_ })
}

Info "Checking dependencies..."
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { Fail "Docker is not installed." }
docker compose version | Out-Null
if ($LASTEXITCODE -ne 0) { Fail "Docker Compose v2 is not available." }

if (-not (Get-Command nvidia-smi -ErrorAction SilentlyContinue)) {
    Warn "No NVIDIA GPU detected. KnowTwin's tei (Jina v4 embeddings) needs CUDA."
    $r = Read-Host "Continue anyway? [y/N]"
    if ($r -notmatch '^[Yy]') { exit 1 }
}

if (Test-Path .env) {
    Warn ".env already exists. Overwriting resets all secrets."
    $r = Read-Host "Continue? [y/N]"
    if ($r -notmatch '^[Yy]') { Info "Keeping existing .env."; exit 0 }
}

Info "Generating secrets..."
$DbPass    = New-HexSecret 16
$JwtSecret = New-HexSecret 32
$ApiPepper = New-HexSecret 32
$Broadcast = New-HexSecret 32
$encBytes  = New-Object byte[] 32
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($encBytes)
$EncKey    = [Convert]::ToBase64String($encBytes).Replace('+','-').Replace('/','_')
$HfCache   = Join-Path $env:USERPROFILE ".cache/huggingface"

$stamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$lines = @(
    "# Generated by setup.ps1 - $stamp"
    "KNOWTWIN_ENV=development"
    "KNOWTWIN_DB_PASSWORD=$DbPass"
    "KNOWTWIN_JWT_SECRET=$JwtSecret"
    "KNOWTWIN_API_KEY_PEPPER=$ApiPepper"
    "KNOWTWIN_CORS_ORIGINS=http://localhost:8090,http://localhost:3001"
    "KNOWTWIN_ENCRYPTION_KEY=$EncKey"
    "KNOWTWIN_INTERNAL_BROADCAST_SECRET=$Broadcast"
    "HF_CACHE_PATH=$HfCache"
)
# UTF-8 WITHOUT BOM — docker compose misparses a .env starting with a BOM.
$content = ($lines -join "`n") + "`n"
$envPath = Join-Path (Get-Location) ".env"
[System.IO.File]::WriteAllText($envPath, $content, (New-Object System.Text.UTF8Encoding $false))
Info ".env generated with random secrets."

if (-not (Test-Path media)) { New-Item -ItemType Directory -Path media | Out-Null }
Info "Created media/ directory."

Write-Host ""
Info "Setup complete. Next steps:"
Write-Host "  1. Start: docker compose up --build -d"
Write-Host "  2. Wait for first boot (models load from HF cache / download on first run)"
Write-Host "  3. Generate an API key: docker exec knowtwin-api python bootstrap_first_apikey.py"
Write-Host "  4. Health check: curl http://localhost:8090/health"
