#!/usr/bin/env bash
# KnowTwin setup — generates .env with random secrets that feed docker-compose.
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

info "Checking dependencies..."
command -v docker >/dev/null 2>&1 || error "Docker is not installed."
command -v openssl >/dev/null 2>&1 || error "openssl is not installed."
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 is not available."

if ! command -v nvidia-smi >/dev/null 2>&1; then
    warn "No NVIDIA GPU detected. KnowTwin's tei (Jina v4 embeddings) needs CUDA."
    read -p "Continue anyway? [y/N] " -n 1 -r; echo
    [[ $REPLY =~ ^[Yy]$ ]] || exit 1
fi

if [ -f .env ]; then
    warn ".env already exists. Overwrite resets all secrets."
    read -p "Continue? [y/N] " -n 1 -r; echo
    [[ $REPLY =~ ^[Yy]$ ]] || { info "Keeping existing .env."; exit 0; }
fi

info "Generating secrets..."
DB_PASS=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
API_PEPPER=$(openssl rand -hex 32)
BROADCAST=$(openssl rand -hex 32)
# Fernet key = urlsafe base64 of 32 random bytes.
ENC_KEY=$(openssl rand -base64 32 | tr '+/' '-_')

cat > .env << EOF
# Generated by setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
KNOWTWIN_ENV=development
KNOWTWIN_DB_PASSWORD=${DB_PASS}
KNOWTWIN_JWT_SECRET=${JWT_SECRET}
KNOWTWIN_API_KEY_PEPPER=${API_PEPPER}
KNOWTWIN_CORS_ORIGINS=http://localhost:8090,http://localhost:3001
KNOWTWIN_ENCRYPTION_KEY=${ENC_KEY}
KNOWTWIN_INTERNAL_BROADCAST_SECRET=${BROADCAST}
# Reuse an existing HuggingFace cache to avoid re-downloading Jina v4 (~7GB).
HF_CACHE_PATH=${HOME}/.cache/huggingface
EOF
chmod 600 .env
info ".env generated with random secrets."

mkdir -p media
info "Created media/ directory."

echo ""
info "Setup complete. Next steps:"
echo "  1. Start: docker compose up --build -d"
echo "  2. Wait for first boot (models load from HF cache / download on first run)"
echo "  3. Generate an API key: docker exec knowtwin-api python bootstrap_first_apikey.py"
echo "  4. Health check: curl http://localhost:8090/health"
